In [1]:
import numpy as np

# Create a 1-dimensional NumPy array with 10 elements of your choice
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1D array:", array_1d)

# Create a 2-dimensional NumPy array with shape (3, 4) containing random integers between 1 and 20
array_2d = np.random.randint(1, 21, (3, 4))
print("2D array (3, 4):", array_2d)

# Reshape the 2D array into a 4x3 array
array_2d_reshaped = array_2d.reshape((4, 3))
print("Reshaped 2D array (4, 3):", array_2d_reshaped)

# Reshape the 2D array into a 1D array
array_1d_reshaped = array_2d.reshape((12,))
print("Reshaped 1D array:", array_1d_reshaped)

# Slice the first 5 elements from the 1D array
sliced_array = array_1d_reshaped[:5]
print("Sliced array:", sliced_array)

# Create an array of zeros with shape (2, 3)
array_zeros = np.zeros((2, 3))
print("Array of zeros (2, 3):", array_zeros)

# Create an array of ones with shape (3, 2)
array_ones = np.ones((3, 2))
print("Array of ones (3, 2):", array_ones)

1D array: [ 1  2  3  4  5  6  7  8  9 10]
2D array (3, 4): [[ 7  2 10 18]
 [ 2  1  1 19]
 [ 3  1 10  3]]
Reshaped 2D array (4, 3): [[ 7  2 10]
 [18  2  1]
 [ 1 19  3]
 [ 1 10  3]]
Reshaped 1D array: [ 7  2 10 18  2  1  1 19  3  1 10  3]
Sliced array: [ 7  2 10 18  2]
Array of zeros (2, 3): [[0. 0. 0.]
 [0. 0. 0.]]
Array of ones (3, 2): [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [2]:
import numpy as np

# Create two 1D arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

# Element-wise addition
print("Element-wise addition:", a + b)

# Element-wise subtraction
print("Element-wise subtraction:", a - b)

# Element-wise multiplication
print("Element-wise multiplication:", a * b)

# Element-wise division
print("Element-wise division:", a / b)


Element-wise addition: [ 7  9 11 13 15]
Element-wise subtraction: [-5 -5 -5 -5 -5]
Element-wise multiplication: [ 6 14 24 36 50]
Element-wise division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [3]:
import numpy as np

# Create two 2D arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Compute the dot product
dot_product = np.dot(A, B)

print("Dot product of A and B:", dot_product)

Dot product of A and B: [[19 22]
 [43 50]]


In [4]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.identity(3)

print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate statistics
sum_array = np.sum(array)
mean_array = np.mean(array)
std_dev_array = np.std(array)
variance_array = np.var(array)

print("Statistics of the 1D Array:")
print(f"Sum: {sum_array}")
print(f"Mean: {mean_array}")
print(f"Standard Deviation: {std_dev_array}")
print(f"Variance: {variance_array}")

Statistics of the 1D Array:
Sum: 55
Mean: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [15]:
import numpy as np

# Create a 1D array with 15 random integers between 0 and 50
array = np.random.randint(0, 51, 15)
print("Original Array:")
print(array)

# Use Boolean indexing to filter out all elements greater than 25 and print the result
filtered_array = array[array <= 25]
print("\nArray with elements <= 25:")
print(filtered_array)

# Replace all values in the array that are less than 10 with 10
array[array < 10] = 10
print("\nArray with values < 10 replaced with 10:")
print(array)

Original Array:
[28  0 26 44 12 26 38 23 21  1 10 40 24 32  7]

Array with elements <= 25:
[ 0 12 23 21  1 10 24  7]

Array with values < 10 replaced with 10:
[28 10 26 44 12 26 38 23 21 10 10 40 24 32 10]


In [16]:
import numpy as np

# Generate a 5x5 matrix with random integers
matrix = np.random.randint(0, 100, (5, 5))
print("Original Matrix:")
print(matrix)

# Find the minimum and maximum values in the matrix
min_val = np.min(matrix)
max_val = np.max(matrix)
print(f"\nMinimum Value: {min_val}, Maximum Value: {max_val}")

# Calculate the row-wise and column-wise sums of the matrix
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("\nRow-wise Sums:")
print(row_sums)
print("\nColumn-wise Sums:")
print(col_sums)

# Create two 2D arrays and stack them vertically and horizontally using NumPy functions
array1 = np.random.randint(0, 100, (3, 3))
array2 = np.random.randint(0, 100, (3, 3))
print("\nArray 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Stack arrays vertically
vertical_stack = np.vstack((array1, array2))
print("\nVertical Stack:")
print(vertical_stack)

# Stack arrays horizontally
horizontal_stack = np.hstack((array1, array2))
print("\nHorizontal Stack:")
print(horizontal_stack)

Original Matrix:
[[94 54 83 84 18]
 [22 96 24 54 28]
 [78 22 92 46 12]
 [56  2 34 82 52]
 [74 61 74 32 83]]

Minimum Value: 2, Maximum Value: 96

Row-wise Sums:
[333 224 250 226 324]

Column-wise Sums:
[324 235 307 298 193]

Array 1:
[[37 28 68]
 [71 38 77]
 [ 2  6 19]]

Array 2:
[[32 96 81]
 [16 33 71]
 [46 25 71]]

Vertical Stack:
[[37 28 68]
 [71 38 77]
 [ 2  6 19]
 [32 96 81]
 [16 33 71]
 [46 25 71]]

Horizontal Stack:
[[37 28 68 32 96 81]
 [71 38 77 16 33 71]
 [ 2  6 19 46 25 71]]
